// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czylcjdruylogqanijys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6eWxjamRydXlsb2dxYW5panlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjAwNDgsImV4cCI6MjA2NzQ5NjA0OH0.wimbK-qs7newZrkykFdJxJky2E_8V4fyItIhEWguuNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    async onAuthStateChange(event, session) {
      if (event === 'SIGNED_IN') {
        // Prefetch user data
        await Promise.all([
          supabase.from('user_preferences').select('*').single(),
          supabase.from('user_progress').select('*').single()
        ]).catch(() => {}); // Ignore errors, they'll be handled by the components
      }
    }
  }
});